#!/bin/bash

# This is a sample DAEMON file which is started at boottime. 
# CAUTION! MAKE SURE YOUR SCRIPT EXITS CLEANLY! It is a good idea
# to start your daemon as background process. If you do something wrong here
# your user's systems may hang forever during boottime!

# Will be executed as user "root".

# Name this file "daemon" in your plugin-archive. It will be renamed to NAME
# during installation

if [ -x /usr/bin/logger ]
then
    /usr/bin/logger "Starting HABridge"
    /usr/bin/java -jar -Dserver.port=8080 -Dconfig.file=/opt/loxberry/data/plugins/p3_lox_habridge2/habridge.config /opt/loxberry/data/plugins/p3_lox_habridge2/habridge.jar > /var/log/habridge 2>&1 &
    /usr/bin/logger "Starting HABridge...done"
fi

exit 0
